### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by muzonff** [lh232510/ChiaMiner#12]
2021-05-12T19:44:20.330 daemon asyncio                    : ERROR    Exception in callback BaseSelectorEventLoop._read_from_self()
handle: <Handle BaseSelectorEventLoop._read_from_self()>
Traceback (most recent call last):
  File "asyncio\events.py", line 88, in _run
  File "asyncio\selector_events.py", line 125, in _read_from_self
ConnectionResetError: [WinError 10054] Удаленный хост принудительно разорвал существующее подключение
2021-05-12T19:44:20.453 daemon asyncio                    : ERROR    Exception in callback BaseSelectorEventLoop._read_from_self()
handle: <Handle BaseSelectorEventLoop._read_from_self()>
Traceback (most recent call last):
  File "asyncio\events.py", line 88, in _run
  File "asyncio\selector_events.py", line 125, in _read_from_self
ConnectionResetError: [WinError 10054] Удаленный хост принудительно разорвал существующее подключение
2021-05-12T19:44:20.455 daemon asyncio                    : ERROR    Exception in callback BaseSelectorEventLoop._read_from_self()

**Comment by muzonff** [comment]
This error occurs after 1-2 hours of use
