### ISSUE TITLE
Error when starting to plot on v0.4.0

### ISSUE THREAD

**Issue by babybatrick** [lh232510/ChiaMiner#14]
After adding directories with my plots, when I click the start button, series of errors appear in the debug log, and the status changes from mining, to not mining. Forced to return to v0.3.2

**Comment by Sergey-Koval** [comment]
Same for me
```
2021-05-14T11:03:13.058 harvester chia.harvester.harvester: ERROR 监测到其他挖矿程序，请关闭其他挖矿程序后启动
2021-05-14T11:03:13.068 harvester asyncio : ERROR unhandled exception during asyncio.run() shutdown
Traceback (most recent call last):
File "asyncio\base_events.py", line 555, in run_until_complete
File "asyncio\base_events.py", line 1758, in _run_once
File "chia\harvester\harvester.py", line 164, in _check_socket_port_task
SystemExit
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "chia\harvester\harvester.py", line 55, in get_sign
File "aiohttp\client.py", line 521, in _request
File "aiohttp\connector.py", line 892, in _create_connection
concurrent.futures._base.CancelledError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "chia\server\start_service.py", line 156, in run
File "chia\harvester\harvester.py", line 144, in _start
2021-05-14T11:03:13.088 harvester asyncio : ERROR Task exception was never retrieved
Traceback (most recent call last):
File "asyncio\base_events.py", line 555, in run_until_complete
File "asyncio\base_events.py", line 1758, in _run_once
File "chia\harvester\harvester.py", line 164, in _check_socket_port_task
SystemExit
```

**Comment by LeksLuter** [comment]
exactly the same error

**Comment by Ivan239** [comment]
same error

**Comment by StuckInLoop** [comment]
监测到其他挖矿程序，请关闭其他挖矿程序后启动  <---  it says something about it sensed or detected another miner software, so asking u to shut off other miners before starting this program.

**Comment by Ivan239** [comment]
> 监测到其他挖矿程序，请关闭其他挖矿程序后启动 <--- it says something about it sensed or detected another miner software, so asking u to shut off other miners before starting this program.

May be you know how to off chia miner when plotting? There is no button like off or smth

**Comment by Sergey-Koval** [comment]
I had official chia network app running at the time, but plots weren't added for farming in it. Weird that uupool considers this suspicious.

**Comment by Sergey-Koval** [comment]
@Ivan239 try plotting from CLI

**Comment by AleksP** [comment]
VERY! VERY! UNSTABEL version! A lot of error during open connection, JSON error, closing connection.... need restart PC to successful connection without ERROR: unknown account ID!!

**Comment by DefSumkin** [comment]
Нужно отключить программу Chia Bloclchain
