### ISSUE TITLE
Problem when start mining

### ISSUE THREAD

**Issue by Joe-me** [lh232510/ChiaMiner#17]
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "chia\harvester\harvester.py", line 55, in get_sign
File "aiohttp\client.py", line 521, in _request
File "aiohttp\connector.py", line 892, in _create_connection
concurrent.futures._base.CancelledError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "chia\server\start_service.py", line 156, in run
File "chia\harvester\harvester.py", line 144, in _start
2021-05-15T11:15:50.757 harvester asyncio : ERROR Task exception was never retrieved
Traceback (most recent call last):
File "asyncio\base_events.py", line 555, in run_until_complete
File "asyncio\base_events.py", line 1758, in _run_once
File "chia\harvester\harvester.py", line 164, in _check_socket_port_task
SystemExit

**Comment by Joe-me** [comment]
Now I have encountered a new issue.

harvester chia.harvester.harvester: ERROR 获取用户签名失败，请重启挖矿程序: Cannot connect to host 47.111.157.136:10086 ssl:default [Connect call failed ('47.111.157.136', 10086)]

As I translated which means to restart, but still cannot start mining

**Comment by AleksP** [comment]
Now you need to restart your PC all time when any errors occurs )
