### ISSUE TITLE
ERROR 获取用户签名失败，请重启挖矿程序

### ISSUE THREAD

**Issue by AleksP** [lh232510/ChiaMiner#20]
2021-05-15T13:48:14.396 harvester chia.harvester.harvester: INFO chuwt: 版本校验：2.1.2
2021-05-15T13:48:14.397 harvester chia.harvester.harvester: INFO 信息打印: accountKey: *********HIDDEN*********, hostname: DESKTOP-UDU8MOK
2021-05-15T13:48:14.417 harvester chia.harvester.harvester: ERROR 获取用户签名失败，请重启挖矿程序:
2021-05-15T13:48:14.418 harvester asyncio : ERROR unhandled exception during asyncio.run() shutdown
Traceback (most recent call last):
File "asyncio\base_events.py", line 555, in run_until_complete
File "asyncio\base_events.py", line 1758, in _run_once
File "chia\harvester\harvester.py", line 164, in _check_socket_port_task
SystemExit
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "chia\harvester\harvester.py", line 55, in get_sign
File "aiohttp\client.py", line 521, in _request
File "aiohttp\connector.py", line 892, in _create_connection
concurrent.futures._base.CancelledError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "chia\server\start_service.py", line 156, in run
File "chia\harvester\harvester.py", line 144, in _start
2021-05-15T13:48:14.429 harvester asyncio : ERROR Task exception was never retrieved
Traceback (most recent call last):
File "asyncio\base_events.py", line 555, in run_until_complete
File "asyncio\base_events.py", line 1758, in _run_once
File "chia\harvester\harvester.py", line 164, in _check_socket_port_task
SystemExit

Again and again! 1-2 hours works then error occurs. Then i reboot PC and the same again, works 1-2h and error...

**Comment by AleksP** [comment]
Only one way i see now is to go another pool!
