### ISSUE TITLE
it doesn't work!!

### ISSUE THREAD

**Issue by Nikolai-007** [lh232510/ChiaMiner#29]
2021-05-16T11:06:33.291 harvester chia.harvester.harvester: ERROR 获取用户签名失败，请重启挖矿程序:
task: <Task finished coro=<async_run_service() done, defined at chia\server\start_service.py:210> exception=RuntimeError('获取用户签名失败，请重启挖矿程序')>
File "asyncio\runners.py", line 43, in run
File "asyncio\base_events.py", line 523, in run_forever
File "asyncio\events.py", line 88, in _run
File "chia\harvester\harvester.py", line 119, in check_socket_port
File "chia\harvester\harvester.py", line 133, in _start
File "aiohttp\client.py", line 1117, in __aenter__
File "aiohttp\connector.py", line 535, in connect
File "aiohttp\connector.py", line 999, in _create_direct_connection
File "chia\server\start_service.py", line 212, in async_run_service
File "chia\server\start_service.py", line 127, in start
RuntimeError: 获取用户签名失败，请重启挖矿程序
2021-05-16T11:06:33.329 harvester asyncio : ERROR Task exception was never retrieved
Traceback (most recent call last):
File "asyncio\base_events.py", line 555, in run_until_complete
File "asyncio\base_events.py", line 1758, in _run_once
File "chia\harvester\harvester.py", line 164, in _check_socket_port_task
SystemExit

**Comment by papaas8888** [comment]
тоже самое

**Comment by akokarev** [comment]
Подписывайтесь на CRC pool https://chia.net.ru/

**Comment by papaas8888** [comment]
Когда старт?

вс, 16 мая 2021 г., 15:16 Anton Kokarev ***@***.***>:

**Comment by akokarev** [comment]
> Когда старт?

После выхода официального API, не раньше
