### ISSUE TITLE
Ubuntu Server 20.04 - Failed to execute script start

### ISSUE THREAD

**Issue by Cornil79** [lh232510/ChiaMiner#5]
Hi! I got an error while starting the miner.. How can this be solved?
![image](https://user-images.githubusercontent.com/28867451/117459550-31a5df80-af54-11eb-8ec0-5cdaa590911d.png)

**Comment by chuwt** [comment]
try to use linux-0.3.2.zip in release

**Comment by aksyonov** [comment]
I have the same error with `linux-0.3.2.zip` on Ubuntu 20.04 in Docker

**Comment by chuwt** [comment]
I'll check it again

**Comment by mihey84s** [comment]
don`t work on Ubuntu 20.04. Daemon not started yet.

**Comment by anufriu** [comment]
same problem for me

**Comment by chuwt** [comment]
try this:

**Comment by chuwt** [comment]
try this:
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
source /etc/profile

**Comment by anufriu** [comment]
same problem. if ill export 2 vars 
 export LC_ALL=en_US.UTF-8
➜  linux-1.4.5 git:(latest) ✗ echo $LC_ALL
en_US.UTF-8
➜  linux-1.4.5 git:(latest) ✗ export LANG=en_US.UTF-8
➜  linux-1.4.5 git:(latest) ✗ echo $LANG
en_US.UTF-8
without making source ill start to get errors from this [https://github.com/lh232510/ChiaMiner/issues/6](issue)
 ./cmd -h
Traceback (most recent call last):
  File "cmd.py", line 223, in <module>
  File "asyncio/base_events.py", line 616, in run_until_complete
  File "cmd.py", line 218, in main
  File "cmd.py", line 29, in help_menu
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-4: ordinal not in range(128)
[176045] Failed to execute script cmd

with source /etc/profile
error is the same 
./cmd start
warning, your CHIA_ROOT is set to .chia. Please unset the environment variable and run chia init again
or manually migrate config.yaml
Chia directory /home/losb/chia-blockchain/uupoll/linux-1.4.5/.chia
后台进程初始化成功, pid:176271
/home/losb/chia-blockchain/uupoll/linux-1.4.5/.chia already exists, no migration action taken
Traceback (most recent call last):
  File "start.py", line 20, in <module>
  File "start.py", line 16, in start_daemon
  File "chia/daemon/server.py", line 1139, in run_daemon
  File "asyncio/base_events.py", line 616, in run_until_complete
  File "chia/daemon/server.py", line 1100, in async_run_daemon
UnicodeEncodeError: 'ascii' codec can't encode characters in position 7-11: ordinal not in range(128)
[176272] Failed to execute script start

**Comment by anufriu** [comment]
@chuwt hello, sorry to bother you, but any updates?

**Comment by anufriu** [comment]
Эни апдейтс ю лэйзи факинг рисовод еь тебя наборот, тебя че из зенитки распиздрячело?
